[package]
name = "rouge"
version = "0.1.0"
edition = "2021"
description = "A statically-typed programming language for applications, plugins, and config files."
readme = "README.md"
license = "LGPL-3.0-or-later"
categories = ["compilers", "command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/runtime/mod.rs"

[dependencies]
logos = "0.12"
logos-nom-bridge = "0.1"
nom = "7.1"
clap = "3.1"
zstd = "0.11"

# The following dependencies are only present in the CLI by default, as they are for GUI. Different libraries for different platforms.

[target.'cfg(linux)'.dependencies]
ui = { version = "0.15", package = "gtk", optional = true }

[target.'cfg(redox)'.dependencies]
ui = { version = "0.2", package = "orbtk", optional = true }

[target.'cfg(darwin)'.dependencies]
ui = { version = "0.2", package = "cacao", optional = true }

[target.'cfg(windows)'.dependencies]
ui = { version = "1.0", package = "native-windows-gui", optional = true }