[package]
name = "rouge"
version = "0.1.0"
edition = "2021"
description = "A statically-typed programming language for applications, plugins, and config files."
readme = "README.md"
license = "LGPL-3.0-or-later"
categories = ["compilers", "command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/runtime/mod.rs"

[dependencies]
# Lexer
logos = "0.12"
# Parser
nom = "7.1"
# Command line interface
clap = { version = "3.1", features = ["cargo", "wrap_help"] }
# Bytecode file compression and decompression.
zstd = "0.11"

# The following dependencies are only present in the standalone utility, as they are for GUI apps. Different libraries for different platforms.

# using gtk for linux gui
[target.'cfg(linux)'.dependencies]
gui = { version = "0.15", package = "gtk", optional = true }

# using orbtk for redox gui
[target.'cfg(redox)'.dependencies]
gui = { version = "0.2", package = "orbtk", optional = true }

# using cacao for macos gui
[target.'cfg(darwin)'.dependencies]
gui = { version = "0.2", package = "cacao", optional = true }

# using native-windows-gui for windows gui
[target.'cfg(windows)'.dependencies]
gui = { version = "1.0", package = "native-windows-gui", optional = true }